### ISSUE TITLE
Scan your buddy's repository

### ISSUE THREAD

**Issue by Hilal-Tapan** [K3A101/real-time-web-2223#13]
Does the repo have an apt description?
Super duper uitgebreide description, very good

Is there a link to the live demo at the top?
Yes

Are any files in the repo that shouldn't be there like an .env file or node_modules?
Nee, ze heeft een gitIgnore

Is there a section about the concept, install notes, data life cycle, external API, and real-time events?
Jaa en heel goed uitgebreid, veel schetsen en proces erin meegenomen.

**Comment by K3A101** [comment]
alles gecontrolleerd
