### ISSUE TITLE
Try to understand the concept

### ISSUE THREAD

**Issue by Hilal-Tapan** [K3A101/real-time-web-2223#14]
**Read about the concept in the readme, do you understand what the app does?**
Jaa, maar je moet wel wat naar beneden om het concept te lezen. Misschien kan je een kort concept stukje wat hoger zetten, onder live demo link bijvoorbeeld.

**Open up the live link (if it's already alive) and play around with the app**
Ziet er heel verzorgt uit! Netjes hoor. Alles is goed uitgewerkt, het is zelfs responsive. Als je een woord invult scrollt die automatisch in scherm en hoef je niet naar beneden te scrollen.

Review the app's functions in an issue, feel free to add cool new ideas in an issue
Ik kan me voorstellen als je met veel in de chat zit je heel veel woorden heel snel krijgt. Misschien als je extra tijd had kon je doen dat je alleen je eigen woorden krijgt te zien. Zodat je niet hoeft te zoeken naar je eigen woord.

Test the app in multiple tabs, does multi-user functionality work as expected?
Ja het werkt

**Comment by K3A101** [comment]
Ik vind het een mooi idee om die functionaliteit toe te voegen. Maar heb ik dat nu in mijn nice to have geplaatst. Ik heb een stukje van mijn concept bovenaan gezet zodat je niet  helemaal beneden moet gaan om die te lezen.
